name: ppx_42 pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  test_and_build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: setup
        run: |
          npm install -g esy@0.5.8
      - name: Print esy cache
        id: print_esy_cache
        run: node .github/workflows/print_esy_cache.js
      - name: Try to restore dependencies cache
        id: esy-cache-win
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v1
        with:
          path: ${{ steps.print_esy_cache.outputs.esy_cache }}
          key: v1-esy-${{ matrix.os }}-${{ hashFiles('**\index.json') }}
      - name: Try to restore dependencies cache
        id: esy-cache-non-win
        if: matrix.os != 'windows-latest'
        uses: actions/cache@v1
        with:
          path: ${{ steps.print_esy_cache.outputs.esy_cache }}
          key: v1-esy-${{ matrix.os }}-${{ hashFiles('**/index.json') }}
      - name: install-build
        run: |
          esy install 
          esy build
